services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stocks"]
      interval: 5s
      timeout: 5s
      retries: 5
  seeder:
    build: ./seeder
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DN_NAME=stocks
      - DB_USER=postgres
      - DB_PASSWORD=postgres
volumes:
  postgres_data: